name: 'YondoMondoMint Deployment'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Service Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Dependencies
        run: yarn install --no-lockfile
      - name: Build
        run: yarn build
      - name: Deploy
        run: aws s3 cp --recursive --region ${{ secrets.AWS_REGION }} dist s3://${{ secrets.AWS_BUCKET_NAME }}
